apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-count-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update-count-pod
  template:
    metadata:
      labels:
        app: update-count-pod
    spec:
      containers:
        - name: update-count-container
          image: update-count:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: UPDATE_COUNT_PORT

            - name: REDIS_STACK_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-variables
                  key: REDIS_STACK_USERNAME

            - name: REDIS_STACK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-variables
                  key: REDIS_STACK_PASSWORD

            - name: REDIS_STACK_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-variables
                  key: REDIS_STACK_HOST

            - name: REDIS_STACK_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-variables
                  key: REDIS_STACK_PORT

            - name: PSQL_URI
              valueFrom:
                secretKeyRef:
                  name: secret-variables
                  key: PSQL_URI

          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: update-count-service
spec:
  selector:
    app: update-count-pod
  ports:
    - port: 5000
      targetPort: 5000
